name: "devrelease:npm"

on:
  push:
    branches:
      - master
      - release-*

jobs:
  publish-canary-npm:
    name: "publish to NPM"
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/playwright-cli'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://registry.npmjs.org'
    - uses: microsoft/playwright-github-action@v1
    - run: npm ci
    - run: |
        git config user.email "devops@playwright.dev"
        git config user.name "playwright-devops"
        npm version "$(node utils/canary_version.js)"
    # - run: npm publish --tag next
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run:
        node -p "require('./package.json').version"
